import os
import fastavro
from sqlite3 import connect

def backup_table_to_avro(table_name, db_path, avro_file_path):
    # Establish a connection to the database
    conn = connect(db_path)
    cursor = conn.cursor()
    
    # Query data from the table
    cursor.execute(f"SELECT * FROM {table_name}")
    records = cursor.fetchall()
    
    # Fetch the column names from the cursor
    column_names = [description[0] for description in cursor.description]
    
    # Define the AVRO schema
    # You might need to adjust the types according to the actual data types of your columns
    schema = {
        'doc': f'Backup of the {table_name} table',
        'name': 'AutoGenerated',
        'type': 'record',
        'fields': [{'name': col_name, 'type': ['null', 'string']} for col_name in column_names],
    }
    
    # Write the records to an AVRO file
    with open(avro_file_path, 'wb') as out:
        fastavro.writer(out, schema, records)
    
    # Close the database connection
    conn.close()

# Example usage
backup_table_to_avro(
    table_name='hired_employees',
    db_path='../db/test_prod.db',
    avro_file_path='../backup/hired_employees.avro'
)