import os
import fastavro
from sqlite3 import connect

def backup_table_to_avro(table_name, db_path, avro_file_path):
    # Establish a connection to the database
    conn = connect(db_path)
    cursor = conn.cursor()
    
    # Query data from the table
    cursor.execute(f"SELECT * FROM {table_name}")
    records = cursor.fetchall()
    
    # Fetch the column names from the cursor
    column_names = [description[0] for description in cursor.description]
    
    # Define the AVRO schema
    # You might need to adjust the types according to the actual data types of your columns
    schema = {
        'doc': f'Backup of the {table_name} table',
        'name': 'AutoGenerated',
        'type': 'record',
        'fields': [{'name': col_name, 'type': ['null', 'string']} for col_name in column_names],
    }
    
    # Write the records to an AVRO file
    with open(avro_file_path, 'wb') as out:
        fastavro.writer(out, schema, records)
    
    # Close the database connection
    conn.close()

def restore_table_from_avro(table_name, db_path, avro_file_path):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Clear the table before restoring
    cursor.execute(f'DELETE FROM {table_name}')
    conn.commit()

    with open(avro_file_path, 'rb') as avro_file:
        reader = fastavro.reader(avro_file)
        records = [record for record in reader]

    # Convert the records to a DataFrame and write to the SQL table
    df = pd.DataFrame(records)
    df.to_sql(table_name, conn, if_exists='replace', index=False)
    conn.commit()
    conn.close()



# Example usage
backup_table_to_avro(
    table_name='hired_employees',
    db_path='../db/test_prod.db',
    avro_file_path='../backup/hired_employees.avro'
)